version: "3.9"

services:
  adempiere.db:
    build:
      context: postgresql/
      dockerfile: Dockerfile
    container_name: ${POSTGRES_NAME}
    restart: ${GENERIC_RESTART}
    ports:
      - ${POSTGRES_PORT}
    volumes:
      - volume_postgres:/var/lib/postgresql/data
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/5432; exit $?;'"
      interval: 60s
      retries: 10
      start_period: 20s
      timeout: 10s
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - adempiere_network
      
  adempiere-zk:
    build:
      context: ../../
      dockerfile: docker/jetty/Dockerfile
    container_name: ${ADEMPIERE_NAME}
    restart: ${GENERIC_RESTART}
    ports:
      - ${ADEMPIERE_ZK_PORT}:8080
    environment:
      ADEMPIERE_DB_SERVER: ${POSTGRES_NAME}
    depends_on:
      adempiere.db:
        condition: service_healthy
    networks:
      - adempiere_network 

networks:
  adempiere_network:
    name: adempiere_network

volumes:
  volume_postgres:
    name: volume_postgres